// <auto-generated />
using System;
using DemoTest.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoTest.DataLayer.Migrations
{
    [DbContext(typeof(TestDemoDbContext))]
    [Migration("20220606072043_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoTest.Domain.Entites.Product.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Tilte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6fdc218-40f0-442e-a484-4849ee41eabe"),
                            Color = 0,
                            Price = 0.0,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("4dddcff6-6b63-4b49-abdf-bc4b67828689"),
                            Color = 1,
                            Price = 0.0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("94477d1a-7d4b-41b3-9d98-b6886b2bf453"),
                            Color = 3,
                            Price = 0.0,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f5d5bb09-4040-4d07-8db6-e51cb6fcba48"),
                            Color = 0,
                            Price = 0.0,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
